/*
	Facultad de Ingenieria en Ciencias de la Computacion y Telecomunicaciones
	UAGRM
	Autor: Anez Vladimirovna Leonardo Henry
	
	Topico: Recursividad
*/

create database Materias;
use Materias;

create table MATERIA
(
	SIGLA VARCHAR(7) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	CREDITOS INT NOT NULL
);

create table PREREQUISITO
(
	SIGLAM VARCHAR(7) NOT NULL,
	SIGLAP VARCHAR(7) NOT NULL,
	PRIMARY KEY (SIGLAM,SIGLAP),
	FOREIGN KEY (SIGLAM) REFERENCES MATERIA(SIGLA)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
	FOREIGN KEY (SIGLAP) REFERENCES MATERIA(SIGLA)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION
);


-- Poblar la Tabla :(
-- SEMESTRE 1
INSERT INTO MATERIA VALUES ('FIS100','FISICA I',6)
INSERT INTO MATERIA VALUES ('INF110','INTRODUCCION A LA INFORMATICA',5)
INSERT INTO MATERIA VALUES ('INF119','ESTRUCTURAS DISCRETAS',5)
INSERT INTO MATERIA VALUES ('LIN100','INGLES TECNICO I',4)
INSERT INTO MATERIA VALUES ('MAT101','CALCULO I',5)
-- SEMESTRE 2
INSERT INTO MATERIA VALUES ('FIS102','FISICA II',6)
INSERT INTO MATERIA VALUES ('INF120','PROGRAMACION I',5)
INSERT INTO MATERIA VALUES ('LIN101','INGLES TECNICO II',4)
INSERT INTO MATERIA VALUES ('MAT102','CALCULO II',5)
INSERT INTO MATERIA VALUES ('MAT103','ALGEBRA LINEAL',5)

INSERT INTO PREREQUISITO VALUES ('FIS102','FIS100')
INSERT INTO PREREQUISITO VALUES ('INF120','INF110')
INSERT INTO PREREQUISITO VALUES ('LIN101','LIN100')
INSERT INTO PREREQUISITO VALUES ('MAT102','MAT101')
INSERT INTO PREREQUISITO VALUES ('MAT103','INF119')

-- SEMESTRE 3
INSERT INTO MATERIA VALUES ('ADM100','ADMINISTRACION',4)
INSERT INTO MATERIA VALUES ('INF210','PROGRAMACION II',5)
INSERT INTO MATERIA VALUES ('INF211','ARQUITECTURA DE COMPUTADORAS',5)
INSERT INTO MATERIA VALUES ('MAT207','ECUACIONES DIFERENCIALES',5)

INSERT INTO PREREQUISITO VALUES ('INF210','MAT103')
INSERT INTO PREREQUISITO VALUES ('INF210','INF120')
INSERT INTO PREREQUISITO VALUES ('INF211','INF120')
INSERT INTO PREREQUISITO VALUES ('INF211','FIS102')
INSERT INTO PREREQUISITO VALUES ('MAT207','MAT102')

-- SEMESTRE 4
INSERT INTO MATERIA VALUES ('ADM200','CONTABILIDAD',4)
INSERT INTO MATERIA VALUES ('INF220','ESTRUCTURA DE DATOS I',5)
INSERT INTO MATERIA VALUES ('INF221','PROGRAMACION ENSAMBLADOR',5)
INSERT INTO MATERIA VALUES ('MAT202','PROBABILIDADES Y ESTADIST.I',5)

INSERT INTO PREREQUISITO VALUES ('ADM200','ADM100')
INSERT INTO PREREQUISITO VALUES ('INF220','MAT101')
INSERT INTO PREREQUISITO VALUES ('INF220','INF210')
INSERT INTO PREREQUISITO VALUES ('INF221','INF211')
INSERT INTO PREREQUISITO VALUES ('MAT202','MAT102')

-- SEMESTRE 5
INSERT INTO MATERIA VALUES ('INF310','ESTRUCTURAS DE DATOS II',5)
INSERT INTO MATERIA VALUES ('INF312','BASE DE DATOS I',5)
INSERT INTO MATERIA VALUES ('INF318','PROGRAMAC.LOGICA Y FUNCIONAL',5)
INSERT INTO MATERIA VALUES ('INF319','LENGUAJES FORMALES',5)
INSERT INTO MATERIA VALUES ('MAT302','PROBABILIDADES Y ESTADISTICAS II',5)

INSERT INTO PREREQUISITO VALUES ('INF310','INF220')
INSERT INTO PREREQUISITO VALUES ('INF312','INF220')
INSERT INTO PREREQUISITO VALUES ('INF318','INF220')
INSERT INTO PREREQUISITO VALUES ('INF319','INF220')
INSERT INTO PREREQUISITO VALUES ('MAT302','MAT202')

-- SEMESTRE 6
INSERT INTO MATERIA VALUES ('INF322','BASES DE DATOS II',5)
INSERT INTO MATERIA VALUES ('INF323','SISTEMAS OPERATIVOS I',5)
INSERT INTO MATERIA VALUES ('INF329','COMPILADORES',5)
INSERT INTO MATERIA VALUES ('INF342','SISTEMAS DE INFORMACION I',5)
INSERT INTO MATERIA VALUES ('MAT329','INVESTIG. OPERATIVA I',5)

INSERT INTO PREREQUISITO VALUES ('INF322','INF312')
INSERT INTO PREREQUISITO VALUES ('INF323','INF310')
INSERT INTO PREREQUISITO VALUES ('INF329','INF310')
INSERT INTO PREREQUISITO VALUES ('INF329','INF319')
INSERT INTO PREREQUISITO VALUES ('INF342','INF312')
INSERT INTO PREREQUISITO VALUES ('MAT329','MAT302')

-- SEMESTRE 7
INSERT INTO MATERIA VALUES ('INF412','SISTEMAS DE INFORMACION II',5)
INSERT INTO MATERIA VALUES ('INF413','SISTEMAS OPERATIVOS II',5)
INSERT INTO MATERIA VALUES ('INF418','INTELIGENCIA ARTIFICIAL',5)
INSERT INTO MATERIA VALUES ('INF433','REDES I',5)
INSERT INTO MATERIA VALUES ('MAT419','INVESTIGAC.OPERATIVA II',5)

INSERT INTO PREREQUISITO VALUES ('INF412','INF342')
INSERT INTO PREREQUISITO VALUES ('INF412','INF322')
INSERT INTO PREREQUISITO VALUES ('INF413','INF323')
INSERT INTO PREREQUISITO VALUES ('INF418','INF310')
INSERT INTO PREREQUISITO VALUES ('INF418','INF318')
INSERT INTO PREREQUISITO VALUES ('INF433','INF323')
INSERT INTO PREREQUISITO VALUES ('MAT419','MAT329')

-- SEMESTRE 8
INSERT INTO MATERIA VALUES ('ECO449','PREPARAC.Y EVALUAC.DE PROYECTOS',5)
INSERT INTO MATERIA VALUES ('INF422','INGENIERIA DE SOFTWARE I',5)
INSERT INTO MATERIA VALUES ('INF423','REDES II',5)
INSERT INTO MATERIA VALUES ('INF428','SISTEMAS EXPERTOS',5)
INSERT INTO MATERIA VALUES ('INF442','SISTEMAS DE INFORM.GEOGRAFICA',4)

INSERT INTO PREREQUISITO VALUES ('ECO449','MAT419')
INSERT INTO PREREQUISITO VALUES ('INF422','INF412')
INSERT INTO PREREQUISITO VALUES ('INF423','INF433')
INSERT INTO PREREQUISITO VALUES ('INF428','INF412')
INSERT INTO PREREQUISITO VALUES ('INF428','INF418')
INSERT INTO PREREQUISITO VALUES ('INF442','INF412')

-- SEMESTRE 9

INSERT INTO MATERIA VALUES ('INF511','TALLER DE GRADO I',5)
INSERT INTO MATERIA VALUES ('INF512','INGENIERIA DE SOFTWARE II',5)
INSERT INTO MATERIA VALUES ('INF513','TECNOLOGIA WEB',5)
INSERT INTO MATERIA VALUES ('INF552','ARQUITECTURA DEL SOFTWARE',4)

-- SEMESTRE 10
INSERT INTO MATERIA VALUES ('INF521','TALLER DE GRADO II',5)

-- khe?
INSERT INTO MATERIA VALUES ('MAT205','METODOS NUMERICOS',5)




select * from PREREQUISITO
