/*
	Facultad de Ingenieria en Ciencias de la Computacion y Telecomunicaciones
	UAGRM
	Autor: Anez Vladimirovna Leonardo Henry
	
	Topico: Recursividad
*/

create database Materias;
use Materias;

create table MATERIA
(
	SIGLA VARCHAR(7) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	CREDITOS INT NOT NULL
);

create table PREREQUISITO
(
	SIGLAM VARCHAR(7) NOT NULL,
	SIGLAP VARCHAR(7) NOT NULL,
	PRIMARY KEY (SIGLAM,SIGLAP),
	FOREIGN KEY (SIGLAM) REFERENCES MATERIA(SIGLA)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
	FOREIGN KEY (SIGLAP) REFERENCES MATERIA(SIGLA)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION
);

INSERT INTO MATERIA VALUES ('FIS100','FISICA I',6)
INSERT INTO MATERIA VALUES ('FIS100','INTRODUCCION A LA INFORMATICA',6)
INSERT INTO MATERIA VALUES ('FIS100','CALCULO I',6)
INSERT INTO MATERIA VALUES ('FIS100','INGLES I',6)
INSERT INTO MATERIA VALUES ('FIS100','ESTRUCTURAS DISCRETAS',6)

-- Poblar la Tabla :(

